### PR TITLE
Dashboard Org Role and Permissions

### PR DESCRIPTION
**Pull request by Thurfjell**
[comment]: <> (This file has been added on OGCIO fork)
### Ticket:

- [23640](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/23640)

### Description

Please include a summary of the changes and the related issue.

## Type

- [ ] **Dependency upgrade**
- [ ] **Bug fix**
- [ ] **New feature**
- [x] **Dev change**

### Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works

### Screenshots:

N/A

### CODE REVIEW

**Review by SamSalvatico — COMMENTED** [review]
We just need it locally?

**Comment by Thurfjell** [comment]
> We just need it locally?

> We just need it locally?

Yep just got confirmed. Will update. Thanks.

**Review by SamSalvatico — APPROVED** [review]

**Review by SamSalvatico — COMMENTED** [review]
this file is for prod

for dev you must use the `-testing` one

**Comment by Thurfjell** [comment]
> this file is for prod
> 
> for dev you must use the `-testing` one

Oh wow alright thanks, thought -testing was for e2e tests for some reason.

**Comment by Thurfjell** [comment]
To be clear, after checking, we want the seeds for all three environments.

**Review by SamSalvatico — APPROVED** [review]

**Review by matteolc — APPROVED** [review]

**Pull request merged**
