### PR TITLE
feat(cli): seed analytics sdk

### PR DESCRIPTION
**Pull request by alewin**
[comment]: <> (This file has been added on OGCIO fork)
### Ticket:

- [20339](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/20339)

### Description

Add seed for analytics SDK logto integration
Related to: https://github.com/ogcio/life-events-terraform/pull/127
## Type

- [ ] **Dependency upgrade**
- [ ] **Bug fix**
- [x] **New feature**
- [ ] **Dev change**

### Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works

### Screenshots:

N/A

### CODE REVIEW

**Review by andreacappadona17 — APPROVED** [review]
LGTM, @edge33 could you please have a look at it, too?

**Review by SamSalvatico — CHANGES_REQUESTED** [review]
You have to also add it to `ogcio-seeder-testing.json`

**Comment by alewin** [comment]
> You have to also add it to `ogcio-seeder-testing.json`

@SamSalvatico 
I haven't added anything on testing voluntarily, also the already existing part of "analytics:mesurable" is currently not added on testing file, because i have not started testing it yet. but if it is mandatory I will add it and then modify it as needed in the future

**Comment by SamSalvatico** [comment]
It's not mandatory, that's fine if you know about it but you don't need it
👍

Il ven 13 set 2024, 11:11 Alessio Koci ***@***.***> ha
scritto:

**Review by SamSalvatico — APPROVED** [review]

**Pull request merged**
